include: package:pedantic_mono/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/firebase_options.dart"
  errors:
        sort_pub_dependencies: false
        use_setters_to_change_properties: false
