name: meditation_life
description: A new Flutter project.

publish_to: 'none'
version: 1.0.3

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI
  animated_bottom_navigation_bar: ^1.2.0
  table_calendar: ^3.0.9
  day_night_time_picker: ^1.3.0+1

  # State
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.4

  # Firebase
  firebase_core: ^2.16.0
  cloud_firestore: ^4.9.2
  firebase_auth: ^4.15.3
  firebase_crashlytics: ^3.4.8

  # DB
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  shared_preferences: ^2.2.1

  # Advertisement
  google_mobile_ads: ^4.0.0

  # Other
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.2
  package_info_plus: ^5.0.1
  flutter_svg: ^2.0.7
  flutter_launcher_icons: ^0.13.1

  # Local Notification
  flutter_local_notifications: ^16.3.0

  # Audio
  just_audio: ^0.9.35

  # Timezone
  timezone: ^0.9.2
  flutter_timezone: ^1.0.7

  cupertino_icons: ^1.0.6
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3

flutter_gen:
  output: lib/core/gen

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.24.0+1
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.7
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  riverpod_generator: 2.3.3

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icons/app_logo.png'
  adaptive_icon_background: '#232323'
  adaptive_icon_foreground: 'assets/icons/app_logo_android.png'

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/svg/
